### ISSUE TITLE
NewtonSoft.json Not Included in Project

### ISSUE THREAD

**Issue by Fried-man** [zachlloyd01/MagicGame#1]
Unity Error: 
> Assets\Scripts\During_Dev\Create_Cards.cs(2,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

You reference NewtonSoft.json on line 2 of Create_Cards.cs but its nowhere in the actual project. It must be on your computer somewhere else so it doesn't error for you. @zachlloyd01 add it to the project folder and it shouldn't error anymore.

**Comment by zachlloyd01** [comment]
Its a VS plugin just install it

**Comment by Fried-man** [comment]
I'm not using VS. I tried installing the JSON but it only installs for specific solutions. Why don't we just use the system default JSON editing code?

**Comment by zachlloyd01** [comment]
NewtonSoft made a custom deserializer that is very quick -- I will switch to the Unity one instead. Give me a bit
