### ISSUE TITLE
Read Array List from JSON file

### ISSUE THREAD

**Issue by zachlloyd01** [zachlloyd01/MagicGame#2]
Unity's built in JSON reader cannot handle JSON arrays -- we need a way to iterate through this. I wrote a helper class, but it is not working.

**Comment by Fried-man** [comment]
Clean data first before we make a custom solution?

**Comment by zachlloyd01** [comment]
Still doesn't solve the problem of the array.

**Comment by Fried-man** [comment]
I can program my own JSON reader. But before that, I need to know exactly what I'm using it for.

**Comment by zachlloyd01** [comment]
I think I can try using the Javascriptserializer class -- I wanna try that
before you put in all that time

**Comment by Fried-man** [comment]
namespace issue fixed.
